import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ArrowRight,ArrowLeft,ArrowDown,BusFront,House,Compass,Route,Bookmark,MapPin,Search,Check,Plus,Minus,LocateFixed,ChevronRight,Footprints,X,Bell,Flag,SlidersHorizontal} from 'lucide-react';
import L from 'leaflet';
import {JourneyPlan,LiveTravel} from './live-service.js';
import {courses,NadriHome,NadriExplore} from './nadri.js';
import './nadri.css';
import {NationalTicket,StartGate,BadgeShelf} from './national-trip.js';

const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const put=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const Icon=({as:C,...p})=><C size={20} strokeWidth={1.8} aria-hidden="true" {...p}/>;
function MapCanvas({point= courses[0].point,paths=[],children}){const host=useRef(),map=useRef(),marker=useRef();const [failed,setFailed]=useState(false);useEffect(()=>{const m=L.map(host.current,{zoomControl:false,attributionControl:true,scrollWheelZoom:false}).setView(point,14);map.current=m;const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(m);tiles.on('tileerror',()=>setFailed(true));marker.current=L.circleMarker(point,{radius:9,color:'#fff',weight:4,fillColor:'#137a64',fillOpacity:1}).addTo(m);const obs=new ResizeObserver(()=>m.invalidateSize());obs.observe(host.current);return()=>{obs.disconnect();m.remove()}},[]);useEffect(()=>{map.current?.flyTo(point,14,{duration:.35});marker.current?.setLatLng(point)},[point[0],point[1]]);useEffect(()=>{if(!map.current||!paths.length)return;const group=L.layerGroup().addTo(map.current);const all=[];paths.forEach(p=>{if(p.coords.length>1){L.polyline(p.coords,{color:p.kind==='ride'?'#167b66':'#d57840',weight:4,opacity:.85,dashArray:p.kind==='ride'?undefined:'5 7'}).addTo(group);all.push(...p.coords)}});if(all.length)map.current.fitBounds(all,{padding:[38,45],maxZoom:15});return()=>group.remove()},[paths]);return <div className="map-canvas"><div ref={host} className="map-inner" aria-label="여행지 위치 지도"/>{failed&&<span className="map-fail">지도를 불러오지 못했어요</span>}<a className="map-credit" href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap</a><div className="map-controls"><button aria-label="지도 확대" onClick={()=>map.current.zoomIn()}><Icon as={Plus}/></button><button aria-label="지도 축소" onClick={()=>map.current.zoomOut()}><Icon as={Minus}/></button><button aria-label="여행지 중심으로" onClick={()=>map.current.setView(point,14)}><Icon as={LocateFixed}/></button></div>{children}</div>}
function Header({page,go,openSaved}){return <header className="header"><button className="brand" onClick={()=>go('home')} aria-label="버스로 잇다 홈"><span className="brand-mark"><Icon as={BusFront} size={21}/></span>버스로 잇다<span className="brand-dot"/></button><div className="header-actions"><a href="/opendesign/mockups/busro-itda-glass/index.html">노선 검색<ArrowUpRight size={13}/></a><button className="icon-button" onClick={openSaved} aria-label="저장한 여행"><Icon as={Bookmark}/></button></div></header>}
function Modes({mode,setMode}){return <div className="modes" role="tablist" aria-label="여행 모드"><button role="tab" aria-selected={mode==='long'} onClick={()=>setMode('long')}><Icon as={Route}/>국토종주</button><button role="tab" aria-selected={mode==='local'} onClick={()=>setMode('local')}><Icon as={Compass}/>나드리</button></div>}
function Home({mode,setMode,go,select,openPlan,saved,toggleSave,trip}){return <div className="home scroll"><div className="home-intro"><span className="location"><Icon as={MapPin} size={14}/>시내버스로 떠나는 여행</span><h1>다음 정류장은,<br/><span>어떤 풍경일까요?</span></h1><button className="search-launch" onClick={openPlan}><Icon as={Search}/><span>출발·도착 정류장 찾기</span><ArrowUpRight size={19}/></button></div><Modes mode={mode} setMode={setMode}/>{mode==='long'?<NationalTicket {...{trip,openPlan,go}}/>:<NadriHome {...{select,saved,toggleSave}}/>}</div>}
function Records({saved,history,tab,setTab,select,toggleSave,trip}){const list=courses.filter(c=>saved.includes(c.id));return <div className="records scroll"><span className="small-caps">MY JOURNEY</span><h1>내가 담아둔 길</h1><div className="record-tabs"><button className={tab==='saved'?'active':''} onClick={()=>setTab('saved')}>저장한 여행 <span>{list.length}</span></button><button className={tab==='done'?'active':''} onClick={()=>setTab('done')}>다녀온 여행 <span>{history.length}</span></button></div>{tab==='saved'?(list.length?list.map(c=><div className="record-row" key={c.id}><button onClick={()=>select(c)}><span className="place-symbol"><MapPin size={22}/></span><span><small>{c.area}</small><strong>{c.title}</strong><span>{c.tag}</span></span></button><button className="icon-button saved" aria-label={`${c.title} 저장 해제`} onClick={()=>toggleSave(c.id)}><Bookmark size={19}/></button></div>):<div className="empty compact"><Bookmark size={30}/><h2>마음에 든 길을 담아보세요.</h2><p>여행지의 저장 버튼을 누르면 여기에 모여요.</p></div>):(history.length?history.map((c,i)=><div className="completed-row" key={i}><span className="stamp"><Check size={22}/></span><div><small>직접 완료 · {c.date}</small><h2>{c.title}</h2><p>{c.stops.join(' → ')}</p></div></div>):<div className="empty compact"><Flag size={30}/><h2>첫 여행을 기다리는 중</h2><p>여행을 마치면 지나온 길이 남아요.</p></div>)}<BadgeShelf {...{history,trip}}/><p className="local-note">저장과 기록은 이 브라우저에 보관됩니다.</p></div>}
function App(){const [seed,setSeed]=useState(null);const [page,setPage]=useState('home'),[mode,setMode]=useState(read('busro-mode-v4','long')),[selected,setSelected]=useState(courses[0]),[saved,setSaved]=useState(read('busro-saved-v4',[])),[trip,setTrip]=useState(read('busro-trip-v4',null)),[history,setHistory]=useState(read('busro-history-v4',[])),[plan,setPlan]=useState(false),[recordTab,setRecordTab]=useState('saved'),[toast,setToast]=useState('');useEffect(()=>put('busro-mode-v4',mode),[mode]);useEffect(()=>put('busro-saved-v4',saved),[saved]);useEffect(()=>put('busro-trip-v4',trip),[trip]);useEffect(()=>put('busro-history-v4',history),[history]);useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2000);return()=>clearTimeout(t)}},[toast]);useEffect(()=>{const f=e=>{if(e.key==='Escape')setPlan(false)};document.addEventListener('keydown',f);return()=>document.removeEventListener('keydown',f)},[]);const go=p=>setPage(p);const select=c=>{setSelected(c);setMode('local');setPage('explore')};const toggleSave=id=>{setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);setToast(saved.includes(id)?'저장을 해제했어요':'여행을 저장했어요')};const start=c=>{if(!c.live){setSeed({title:c.title,query:c.query,city_code:c.city_code});setPlan(true);return;}if(trip?.startCheck){setToast('진행 중인 여행을 먼저 마쳐주세요');return;}setTrip({...c,instanceId:crypto.randomUUID()});setPlan(false);setPage(c.mode==='long'?'home':'travel')};const finish=c=>{setHistory(h=>h.some(t=>c.instanceId&&t.instanceId===c.instanceId)?h:[{...c,date:new Date().toLocaleDateString('ko-KR')},...h]);setTrip(null);setRecordTab('done');setPage('record')};return <div className="app-shell"><Header page={page} go={go} openSaved={()=>{setRecordTab('saved');go('record')}}/><main className="main-view" key={page}>{page==='home'?<Home {...{mode,setMode,go,select,saved,toggleSave,trip}} openPlan={()=>{setSeed(null);setPlan(true)}}/>:page==='explore'?<NadriExplore {...{selected,select,start,saved,toggleSave,MapCanvas}}/>:page==='travel'?(trip?.mode==='long'&&!trip.startCheck?<StartGate key={trip.instanceId||trip.id} trip={trip} onStart={setTrip}/>:<LiveTravel {...{trip,finish,go,MapCanvas}}/>):<Records {...{saved,history,select,toggleSave,trip}} tab={recordTab} setTab={setRecordTab}/>}</main><nav className="bottom-nav" aria-label="주요 메뉴">{[['home',House,'홈'],['explore',Compass,'탐색'],['travel',BusFront,'여행 중'],['record',Bookmark,'내 기록']].map(([id,C,label])=><button key={id} onClick={()=>go(id)} aria-current={page===id?'page':undefined}><span><Icon as={C} size={22}/>{id==='travel'&&trip&&<i/>}</span>{label}</button>)}</nav>{plan&&<JourneyPlan close={()=>setPlan(false)} {...{start,seed,mode}}/>}<div className="toast-wrap" role="status">{toast&&<div className="toast"><Check size={17}/>{toast}</div>}</div></div>}
createRoot(document.getElementById('app')).render(<App/>);
