import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const places=JSON.parse(await readFile(new URL('./data/nadri.generated.json',import.meta.url))).places;
const base=process.env.CHECK_URL||'http://127.0.0.1:8289/opendesign/mockups/busro-travel/';
const browser=await chromium.launch({executablePath:'C:/Users/user/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe',headless:true});
const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[],calls=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/api/'))calls.push(r.url())});
if(base.includes('127.0.0.1'))await page.route('**/api/**',async route=>{const req=route.request();try{const response=await route.fetch({url:'https://busro-itda.vercel.app'+new URL(req.url()).pathname+new URL(req.url()).search,headers:{...req.headers(),origin:'https://busro-itda.vercel.app'}});await route.fulfill({response})}catch{await route.abort()}});
const shot=async name=>{await page.screenshot({path:`C:/Users/user/Documents/Codex/2026-08-31/new-chat-3/outputs/nadri-${name}.png`})};
await page.goto(base);await page.getByRole('tab',{name:'나드리',exact:true}).click();assert.equal(await page.locator('.feed-slide').count(),places.length);await shot('home-390');
await page.locator('.feed-slide[aria-hidden=false] .feed-story').click();await page.getByRole('button',{name:'코스 저장',exact:true}).click();await page.getByRole('button',{name:'방문 유의사항 · 출처 보기'}).click();assert((await page.locator('.nadri-details a').count())>=2);assert((await page.locator('.nadri-details').innerText()).includes('정류장입니다'));await page.locator('.nadri-details').scrollIntoViewIfNeeded();await shot('details-390');
await page.getByRole('button',{name:'도착 정류장으로 경로 찾기'}).click();assert.equal(await page.getByLabel('도착 정류장 검색',{exact:true}).inputValue(),'대청댐');await page.waitForRequest(r=>r.url().includes('city_code=25'),{timeout:15000}).catch(()=>assert(calls.some(x=>x.includes('city_code=25'))));await page.getByRole('button',{name:'닫기',exact:true}).click();await page.getByRole('button',{name:'내 기록',exact:true}).click();assert.equal(await page.locator('.record-row').count(),1);await page.reload();await page.getByRole('button',{name:'내 기록',exact:true}).click();assert.equal(await page.locator('.record-row').count(),1);
await page.getByRole('button',{name:'탐색',exact:true}).click();await page.getByRole('button',{name:'청주',exact:true}).click();assert.equal(await page.locator('.nadri-results>button').count(),places.filter(p=>p.region==='청주').length);await page.getByLabel('나드리 풍경').selectOption('숲·수목원');assert.equal(await page.locator('.nadri-results>button').count(),1);await page.locator('.nadri-results>button').click();assert((await page.locator('.sheet-title').innerText()).includes('미동산수목원'));await page.getByRole('button',{name:'도착 정류장으로 경로 찾기'}).click();assert.equal(await page.getByLabel('도착 정류장 검색',{exact:true}).inputValue(),'미동산수목원');await page.waitForRequest(r=>r.url().includes('city_code=33010'),{timeout:15000}).catch(()=>assert(calls.some(x=>x.includes('city_code=33010'))));await page.getByRole('button',{name:'닫기',exact:true}).click();
await page.getByLabel('여행지 검색').fill('대청댐');assert.equal(await page.locator('.nadri-results>button').count(),0);await page.getByRole('button',{name:'전체',exact:true}).click();await page.getByLabel('나드리 풍경').selectOption('전체');assert.equal(await page.locator('.nadri-results>button').count(),1);await page.locator('.nadri-results>button').click();await shot('explore-390');
for(const [width,height] of [[360,800],[390,844],[1440,900]]){await page.setViewportSize({width,height});assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)));await page.getByRole('button',{name:'도착 정류장으로 경로 찾기'}).scrollIntoViewIfNeeded();assert(await page.getByRole('button',{name:'도착 정류장으로 경로 찾기'}).isVisible());await shot('explore-'+width);await page.getByRole('button',{name:'홈',exact:true}).click();await page.locator('.feed-slide[aria-hidden=false]').scrollIntoViewIfNeeded();assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)));await shot('home-bottom-'+width);await page.getByRole('button',{name:'탐색',exact:true}).click();}
assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,places:places.length,checks:['source expansion','saved reload','region/theme/query intersection','city-scoped destination seed','360/390/1440 no overflow','CTA reachable'],apiCalls:calls,errors}));await browser.close();
